export const ENV_KEYS = {
  PORT: 'PORT',
  DATABASE: {
    HOST: 'DATABASE_HOST',
    PORT: 'DATABASE_PORT',
    USERNAME: 'DATABASE_USER',
    PASSWORD: 'DATABASE_PASSWORD',
    NAME: 'DATABASE_NAME',
  },
  NODE_ENV: 'NODE_ENV',
  BCRYPT_SALT_ROUNDS: 'BCRYPT_SALT_ROUNDS',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION_TIME: 'JWT_EXPIRATION_TIME',
};
